// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "gameoflife_ui.h"

Gameoflife_UI::Gameoflife_UI() {
  { _window = new Fl_Double_Window(640, 540, "Game of Life");
    _window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 0, 640, 480);
      { _gol_grid = new Grid_Widget(0, 0, 640, 480, "Grid Widget");
        _gol_grid->box(FL_NO_BOX);
        _gol_grid->color(FL_BACKGROUND_COLOR);
        _gol_grid->selection_color(FL_BACKGROUND_COLOR);
        _gol_grid->labeltype(FL_NORMAL_LABEL);
        _gol_grid->labelfont(0);
        _gol_grid->labelsize(14);
        _gol_grid->labelcolor(FL_FOREGROUND_COLOR);
        _gol_grid->align(Fl_Align(FL_ALIGN_CENTER));
        _gol_grid->when(FL_WHEN_RELEASE);
      } // Grid_widget* _gol_grid
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(0, 455, 640, 85);
      { _go_button = new Fl_Button(280, 495, 80, 25, "Go");
      } // Fl_Button* _go_button
      { _clear_button = new Fl_Button(195, 495, 80, 25, "Clear");
      } // Fl_Button* _clear_button
      { _random_button = new Fl_Button(110, 495, 80, 25, "Random");
      } // Fl_Button* _random_button
      { _save_button = new Fl_Button(450, 495, 80, 25, "Save");
      } // Fl_Button* _save_button
      { _load_button = new Fl_Button(365, 495, 80, 25, "Load");
      } // Fl_Button* _load_button
      o->end();
    } // Fl_Group* o
    _window->end();
  } // Fl_Double_Window* _window
  _gol_grid->cell_size(10);
}

/**
 show the window
*/
void Gameoflife_UI::show() {
  _window->show();
}

/**
 get the go button
*/
Fl_Button* Gameoflife_UI::go_button() {
  return _go_button;
}

/**
 get the clear button
*/
Fl_Button* Gameoflife_UI::clear_button() {
  return _clear_button;
}

/**
 get the random button
*/
Fl_Button* Gameoflife_UI::random_button() {
  return _random_button;
}

/**
 get the save button
*/
Fl_Button* Gameoflife_UI::save_button() {
  return _save_button;
}

/**
 get the load button
*/
Fl_Button* Gameoflife_UI::load_button() {
  return _load_button;
}

/**
 get the grid
*/
Grid_Widget * Gameoflife_UI::gol_grid() {
  return _gol_grid;
}
